### ISSUE TITLE
When Dungeons Arise

### ISSUE THREAD

**Issue by Moxiess** [supercharged-modpack/modpack#1]
Thought this mod would add some cool dungeons for exploring and getting loot. Plus these dungeons can be quite difficult, so it would add another level of difficulty into the mod pack. So thats why i thought this would be a good mod to add. But its only curseforge only. Which is the only issue.

**Comment by youmukonpaku1337** [comment]
you could make a github issue on the mod's repo about modrinth support

**Comment by youmukonpaku1337** [comment]
i don't really want to screw with redistribution

**Comment by youmukonpaku1337** [comment]
nevermind, it is on modrinth just doesn't launch
