### ISSUE TITLE
Can't create a new singleplayer world in 5.0.1

### ISSUE THREAD

**Issue by fzzyhmstrs** [supercharged-modpack/modpack#3]
Trying to run some tests for my issue opened earlier, and I can't get a singleplayer world to generate. I'm getting a Datapack error with the following log snippet. Seems to be some error with "powershot"

[Log](https://mclo.gs/NFI39fD)

**Comment by youmukonpaku1337** [comment]
first of all, next time upload to a log site such as https://mclo.gs
second of all, are you sure it works fine without powershot?

**Comment by youmukonpaku1337** [comment]
but yeah looks like it's powershot, try without it

**Comment by youmukonpaku1337** [comment]
if it works without it, guess i'll remove it

**Comment by fzzyhmstrs** [comment]
Partway into successful generation with powershot removed. I have a habit of avoiding log sites because they are almost all completely blocked on my work network. Updated above though.

**Comment by youmukonpaku1337** [comment]
also, do you have the "use system GLFW" option enabled in Poly/MultiMC?

**Comment by youmukonpaku1337** [comment]
you could try enabling that

**Comment by youmukonpaku1337** [comment]
i see some errors related to glfw

**Comment by fzzyhmstrs** [comment]
Can't tell if the system GLFW helps powershot because using that setting crashes REI

**Comment by youmukonpaku1337** [comment]
that's super weird, never has caused any issues with rei or any mod for me, which OS are you running?

**Comment by youmukonpaku1337** [comment]
but anyway, does singleplayer load without powershot?

**Comment by fzzyhmstrs** [comment]
windows 10 home

**Comment by youmukonpaku1337** [comment]
oh okay then i'm not sure

**Comment by youmukonpaku1337** [comment]
so uh, does singleplayer load without powershot?

**Comment by fzzyhmstrs** [comment]
Yes, it did generate the world all the way with powershot disabled.

**Comment by youmukonpaku1337** [comment]
okay, well, no powershot then

**Comment by youmukonpaku1337** [comment]
should be fixed in 5.0.2 when i release

**Comment by youmukonpaku1337** [comment]
wait, 5.1.0 not 5.0.2

**Comment by youmukonpaku1337** [comment]
fixed in 5.1.0
